name: orbit_production

services:
  # Redis
  redis:
    image: redis:7-alpine
    container_name: orbit_redis_production
    restart: unless-stopped
    volumes:
      - nv_redis:/data
    command: redis-server --port 16379

  # Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: orbit-server:production
    container_name: orbit_server_production
    restart: unless-stopped
    ports:
      - "18787:18787"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    volumes:
      - nv_realm:/app/.realm
    depends_on:
      - redis
    tty: true
    stdin_open: true

  # Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: orbit-client:production
    container_name: orbit_client_production
    restart: unless-stopped
    ports:
      - "15173:15173"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    depends_on:
      - server
    tty: true
    stdin_open: true

  # Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: orbit_tunnel_production
    restart: unless-stopped
    env_file:
      - .env
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - server
      - client
volumes:
  nv_redis:
  nv_realm:
